version: '3.8'

services:
  fastapi_app:			# По умолчанию контейнеры создаются в общей сети
    build:
      context: ./fastapi_app	# Dockerfile в папке fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  aiogram_app:			
    build:
      context: ./aiogram_app	# Dockerfile в папке aiogram_app
      dockerfile: Dockerfile

  postgres:
    image: postgres:13
    environment:		# Эти переменные создают БД и пользователя
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
